helmDefaults:
  createNamespace: true
  atomic: false
  verify: false
  wait: false
  timeout: 120
  disableValidation: true

templates:
  default: &default
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    namespace: kdl
    values:
    - "values/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl"
    - "values/{{`{{ .Release.Name }}`}}/values.yaml"

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/
  - name: minio
    url: https://charts.min.io/

releases:
  - name: "mongodb-string-uri"
    <<: *default
    chart: bedag/raw
    version: 2.0.0

  - name: "kdl-local"
    <<: *default
    chart: oci://ghcr.io/konstellation-io/helm-charts/kdl-server
    version: 6.0.3-rc.4
    needs:
    - kdl/mongodb-string-uri

  - name: "mongodb-initial-data"
    <<: *default
    chart: bedag/raw
    version: 2.0.0
    needs:
    - kdl/kdl-local
