environments:
  default:
    values:
      - keycloak_admin_password: "a123456"
      - keycloak_admin_user: "kdladmin"
      - minio_access_key: "minio"
      - minio_secret_key: "minio123"
      - mongodb_password: "123456"
      - mongodb_user: "kdl"
      - mongodb_version: "7.0.15"
---
helmDefaults:
  createNamespace: true
  atomic: false
  verify: false
  wait: false
  timeout: 120
  disableValidation: true

templates:
  default: &default
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    values:
      - "values/{{`{{ .Release.Name }}`}}/values.yaml.gotmpl"
      - "values/{{`{{ .Release.Name }}`}}/values.yaml"

repositories:
  - name: bedag
    url: https://bedag.github.io/helm-charts/
  - name: jetstack
    url: https://charts.jetstack.io
  - name: minio
    url: https://charts.min.io/
  - name: mongodb
    url: https://mongodb.github.io/helm-charts
  - name: emberstack
    url: https://emberstack.github.io/helm-charts
  - name: konstellation-io
    url: registry.gitlab.intelygenz.com
    oci: true
    password: {{ requiredEnv "GITLAB_TOKEN" }}

releases:
  # ref: https://github.com/cert-manager/cert-manager/blob/v1.17.1/deploy/charts/cert-manager/values.yaml
  - name: cert-manager
    chart: jetstack/cert-manager
    version: v1.17.1
    namespace: cert-manager
    inherit:
      - template: default

  - name: cert-manager-clusterissuers
    chart: bedag/raw
    version: 2.0.0
    namespace: cert-manager
    needs:
      - cert-manager
    inherit:
      - template: default

  - name: initial-resources
    chart: bedag/raw
    version: 2.0.0
    namespace: kdl
    inherit:
      - template: default

  # ref: https://github.com/mongodb/helm-charts/blob/community-operator-crds-0.12.0/charts/community-operator-crds/values.yaml
  - name: mongodb-community-operator-crds
    chart: mongodb/community-operator-crds
    version: 0.12.0
    namespace: mongodb-operator
    inherit:
      - template: default

  # ref: https://github.com/mongodb/helm-charts/blob/community-operator-0.12.0/charts/community-operator/values.yaml
  - name: mongodb-community-operator
    chart: mongodb/community-operator
    version: 0.12.0
    namespace: mongodb-operator
    needs:
      - mongodb-operator/mongodb-community-operator-crds
    inherit:
      - template: default

  - name: mongodb-database
    chart: bedag/raw
    version: 2.0.0
    namespace: mongodb
    needs:
      - mongodb-operator/mongodb-community-operator
    inherit:
      - template: default

  - name: mongodb-initial-data
    chart: bedag/raw
    version: 2.0.0
    namespace: mongodb
    needs:
      - kdl/kdl-local
    inherit:
      - template: default

  # ref: https://gitlab.intelygenz.com/konstellation-io/helm-charts/blob/kdl-server-6.2.9/charts/kdl-server/values.yaml
  - name: kdl-local
    chart: oci://registry.gitlab.intelygenz.com/konstellation-io/helm-charts/kdl-server
    version: 6.2.9
    namespace: kdl
    needs:
      - kdl/initial-resources
      - mongodb/mongodb-database
    inherit:
      - template: default

  # ref: https://github.com/minio/minio/blob/RELEASE.2025-02-28T09-55-16Z/helm/minio/values.yaml
  - name: minio
    chart: minio/minio
    version: 5.4.0
    namespace: minio
    needs:
      - kube-system/reflector
    inherit:
      - template: default

  - name: keycloak-initial-data
    chart: bedag/raw
    version: 2.0.0
    namespace: kdl
    needs:
      - kdl/kdl-local
    inherit:
      - template: default

  # ref: https://github.com/emberstack/kubernetes-reflector/blob/v9.0.318/src/helm/reflector/values.yaml
  - name: reflector
    chart: emberstack/reflector
    version: 9.0.318
    namespace: kube-system
    needs:
      - kdl/kdl-local
    inherit:
      - template: default
