// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/konstellation-io/kdl-server/app/api/entity"
)

type CreateProjectInput struct {
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Repository  *RepositoryInput `json:"repository"`
}

type RepositoryInput struct {
	Type entity.RepositoryType `json:"type"`
	URL  string                `json:"url"`
}

type UpdateProjectInput struct {
	ID         string                        `json:"id"`
	Name       *string                       `json:"name"`
	Repository *UpdateProjectRepositoryInput `json:"repository"`
}

type UpdateProjectRepositoryInput struct {
	URL string `json:"url"`
}
