apiVersion: v2
type: application
name: kdl-project
description: A Helm chart to deploy KDL projects
version: 1.0.0
appVersion: 1.37.0
sources:
  - https://github.com/konstellation-io/kdl-server
home: https://www.konstellation.io
maintainers:
  - name: ialejandro
    email: ivan.alejandro@intelygenz.com
  - name: alpiquero
    email: angelluis.piquero@intelygenz.com
  - name: danielchg
    email: daniel.chavero@intelygenz.com
keywords:
  - ia
  - kdl
  - kdl-server
  - konstellation
  - kubernetes
  - machine learning
