apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.projectId }}-filebrowser-config
  labels:
    app:  {{ .Values.projectId }}-filebrowser-config
data:
  .filebrowser.json: |
    {
      "port": 9696,
      "baseURL": "/filebrowser/{{ .Values.projectId }}",
      "address": "0.0.0.0",
      "log": "stdout",
      "database": "/database.db",
      "root": "/srv"
    }

  entrypoint.sh: |
    #!/bin/sh
    /filebrowser config init
    /filebrowser config set --auth.method=noauth
    /filebrowser users add kdladmin not_used_pass --perm.admin=false --perm.download=true --perm.create=true \
        --perm.delete=false --perm.execute=false --perm.modify=false --perm.rename=false --perm.share=false \
        --perm.delete=true --lockPassword=true
    /filebrowser
