apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectId }}-filebrowser
  labels:
    app: {{ .Values.projectId }}-filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.projectId }}-filebrowser
  template:
    metadata:
      labels:
        app: {{ .Values.projectId }}-filebrowser
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    {{- with .Values.filebrowser.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.filebrowser.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.filebrowser.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      containers:
        - name: filebrowser
          image: {{ .Values.filebrowser.image.repository }}:{{ .Values.filebrowser.image.tag }}
          imagePullPolicy: {{ .Values.filebrowser.image.pullPolicy }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          command:
            - /bin/sh
          args:
            - -c
            - /entrypoint.sh
          volumeMounts:
            - name: filebrowser-config
              mountPath: /.filebrowser.json
              subPath: .filebrowser.json
            - name: filebrowser-config
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
            - name: received-data
              mountPath: /srv
              subPath: {{ .Values.projectId }}
          livenessProbe:
            httpGet:
              path: /filebrowser/{{ .Values.projectId }}
              port: 9696
            initialDelaySeconds: 30
            periodSeconds: 60
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      volumes:
        - name: filebrowser-config
          configMap:
            name: {{ .Values.projectId }}-filebrowser-config
            defaultMode: 0777
        - name: received-data
          persistentVolumeClaim:
            claimName: {{ .Values.sharedVolume.name }}-claim
