apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-oauth2
  labels:
    app:  gitea-oauth2
data:
  GITEA_URL: {{ printf "%s://gitea.%s" ( include "http.protocol" . ) .Values.global.domain }}
  GITEA_OAUTH2_AUTHORIZE_URL: {{ printf "%s://gitea.%s/login/oauth/authorize" ( include "http.protocol" . ) .Values.global.domain }}
  GITEA_OAUTH2_TOKEN_URL: {{ printf "%s://gitea.%s/login/oauth/access_token" ( include "http.protocol" . ) .Values.global.domain }}
  GITEA_OAUTH2_USERDATA_URL: {{ printf "%s://gitea.%s/api/v1/user" ( include "http.protocol" . ) .Values.global.domain }}
