kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kdlproject
rules:
  - apiGroups: ["project.konstellation.io"]
    resources: ["kdlprojects","kdlproject"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-kdlproject
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: kdlproject
  apiGroup: rbac.authorization.k8s.io
