kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.sharedVolume.name }}-claim
spec:
  storageClassName: {{ .Values.sharedVolume.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.sharedVolume.size }}
