version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
    - enhancement
    - dependency-management
    - devops-team
  groups:
    github-actions:
      patterns:
        - "*"

- package-ecosystem: gomod
  directories:
    - "/app/api"
    - "/repo-cloner"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  labels:
    - enhancement
    - dependency-management
    - develop-team
  groups:
    golang-dependencies:
      patterns:
        - "*"

- package-ecosystem: docker
  directories:
    - "/app"
    - "/cleaner"
    - "/repo-cloner"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  labels:
    - enhancement
    - dependency-management
    - develop-team
    - devops-team
  groups:
    docker-updates:
      patterns:
        - "*"
