apiVersion: v1
kind: ConfigMap
metadata:
  name: kdl-server-oauth2-proxy
data:
  oauth2_proxy.cfg: |+
    provider="github"
    redirect_url="{{ printf "%s://kdlapp.%s/oauth2/callback" ( include "http.protocol" . ) .Values.global.domain }}"
    login_url="{{ printf "%s://gitea.%s/login/oauth/authorize" ( include "http.protocol" . ) .Values.global.domain }}"
    redeem_url="{{ printf "%s://gitea.%s/login/oauth/access_token" ( include "http.protocol" . ) .Values.global.domain }}"
    validate_url="{{ printf "%s://gitea.%s/api/v1" ( include "http.protocol" . ) .Values.global.domain }}"
    profile_url="{{ printf "%s://gitea.%s/api/v1/user" ( include "http.protocol" . ) .Values.global.domain }}"
    cookie_secret="{{ .Values.oauth2Proxy.config.cookieSecret }}"
    cookie_secure={{ ternary "true" "false" .Values.global.ingress.tls.enabled }}
    cookie_samesite="{{ ternary "none" "lax" .Values.global.ingress.tls.enabled }}"
    ssl_insecure_skip_verify=true
    ssl_upstream_insecure_skip_verify=true
