apiVersion: v1
kind: Secret
metadata:
  name: kdl-server-oauth2
type: Opaque
data:
  DEPLOYMENT_SECRET_NAME: {{ print "kdl-server-oauth2-credentials" | b64enc }}
  GITEA_REDIRECT_URIS: {{ printf "%s://kdlapp.%s/oauth2/callback"  ( include "http.protocol" . ) .Values.global.domain | b64enc }}
  GITEA_APPLICATION_NAME: {{ print "kdl-server" | b64enc }}
