apiVersion: v1
kind: Service
metadata:
  name: kdl-server
  labels:
    app: kdl-server
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: oauth2-proxy
  selector:
    app: kdl-server
