# permissions for end users to view kdlprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kdlproject-viewer-role
rules:
- apiGroups:
  - project.konstellation.io
  resources:
  - kdlprojects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.konstellation.io
  resources:
  - kdlprojects/status
  verbs:
  - get
