# quay.io/operator-framework/helm-operator:v1.38
FROM quay.io/operator-framework/helm-operator@sha256:1efe00bc5cd156f720bbe23c237e974626a23df873d3f40ab9ce3c4e9e394248

LABEL maintainer="Intelygenz - Konstellation Team"

COPY watches.yaml ${HOME}/watches.yaml
COPY helm-charts  ${HOME}/helm-charts
