apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-runner
  labels:
    app:  drone-runner
data:
  DRONE_RUNNER_CAPACITY: "{{ .Values.drone.runnerCapacity }}"
  DRONE_RPC_HOST: drone.{{ .Values.global.domain }}
  DRONE_RPC_PROTO: {{ printf "%s" ( include "http.protocol" . ) }}
  DRONE_NAMESPACE_DEFAULT: {{ .Release.Namespace }}
  DRONE_DEBUG: {{ .Values.droneRunner.debug | quote }}
  DRONE_TRACE: {{ .Values.droneRunner.trace | quote }}
  DRONE_SECRET_PLUGIN_ENDPOINT: http://localhost:3000
  {{- if .Values.droneRunner.droneRunnerEnviron }}
  DRONE_RUNNER_ENVIRON: "{{ .Values.droneRunner.droneRunnerEnviron }}"
  {{- end }}
  {{- if .Values.droneRunner.serviceAccountJob.enabled }}
  DRONE_SERVICE_ACCOUNT_DEFAULT: {{ .Values.droneRunner.serviceAccountJob.name }}
  {{- end }}
