apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: drone-runner
  name: drone-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      run: drone-runner
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/drone-runner/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/drone-runner/secret.yaml") . | sha256sum }}
      labels:
        run: drone-runner
    spec:
      serviceAccountName: drone-runner
      containers:
      - name: secrets
        image: drone/kubernetes-secrets:latest
        ports:
        - containerPort: 3000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: drone-runner
              key: DRONE_SECRET_PLUGIN_TOKEN
        - name: KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace }}
      - name: runner
        image: {{ .Values.droneRunner.image.repository }}:{{ .Values.droneRunner.image.tag }}
        name: drone-runner
        envFrom:
          - configMapRef:
              name: drone-runner
          - secretRef:
              name: drone-runner
      {{- if and .Values.global.ingress.tls.enabled .Values.global.ingress.tls.caSecret }}
        volumeMounts:
        - mountPath: /etc/ssl/certs/ca-cert.pem
          name: ca-cert
          subPath: {{ .Values.global.ingress.tls.caSecret.certFilename }}
      {{- end }}
    {{- with .Values.droneRunner.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.droneRunner.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.droneRunner.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if and .Values.global.ingress.tls.enabled .Values.global.ingress.tls.caSecret }}
      volumes:
      - name: ca-cert
        secret:
          secretName: {{ .Values.global.ingress.tls.caSecret.name }}
    {{- end }}
