{{ if .Values.droneRunner.serviceAccountJob.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.droneRunner.serviceAccountJob.name }}
{{- if .Values.droneRunner.serviceAccountJob.annotations }}
  annotations:
{{ tpl (toYaml .Values.droneRunner.serviceAccountJob.annotations) . | indent 4 }}
{{- end }}
{{ end }}
