apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: drone-runner
  labels:
    app:  drone-runner
data:
  DRONE_RPC_SECRET: {{ .Values.drone.rpcSecret | b64enc }}
  DRONE_SECRET_PLUGIN_TOKEN: {{ .Values.droneRunner.pluginSecret | b64enc }}
