port: "3000"
staticFilesPath: "../public"
logLevel: "debug"
mongodb:
  uri: "mongodb://admin:123456@mongodb:27017/admin"
  dbName: "kdl"
gitea:
  internal_url: "http://localhost:3000"
scheduledJob:
  usersSync:
    interval: 10m
