apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgres.dbName | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.dbPassword | b64enc }}
