apiVersion: v1
kind: Pod
metadata:
  name: restore
  labels:
    name: restore
  namespace: kdl
spec:
  containers:
    - name: restore
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      image: konstellation/kdl-backup:latest
      imagePullPolicy: IfNotPresent
      command:
      - /bin/sh
      - "-c"
      - "sleep 180m"
      envFrom:
        - configMapRef:
            name: gitea-config
        - secretRef:
            name: postgres
        - secretRef:
            name: backup-secrets
      volumeMounts:
      - name: gitea-pvc
        mountPath: "/data"
      - name: shared-storage
        mountPath: /shared-volume
        readOnly: false
      resources:
        limits:
          memory: "512Mi"
          cpu: "1000m"
  volumes:
    - name: gitea-pvc
      persistentVolumeClaim:
        claimName: gitea-pvc-gitea-0
    - name: shared-storage
      hostPath:
        path: /var/snap/microk8s/common/default-storage
        type: Directory
  restartPolicy: OnFailure
