apiVersion: v1
kind: Pod
metadata:
  name: restore
  labels:
    name: restore
  namespace: kre
spec:
  containers:
    - name: restore
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      image: konstellation/kdl-backup:latest
      imagePullPolicy: IfNotPresent
      command:
      - /bin/sh
      - "-c"
      - "sleep 180m"
      # envFrom:
      #   - configMapRef:
      #       name: gitea-config
      #   - secretRef:
      #       name: postgres
      #   - secretRef:
      #       name: backup-secrets
      volumeMounts:
      # - name: gitea-pvc
      #   mountPath: "/data"
      # - name: shared-storage
      #   mountPath: /shared-volume
      #   readOnly: false
        - name: mongo-backup
          mountPath: /mongo-backup
          readOnly: false
      resources:
        limits:
          memory: "512Mi"
          cpu: "1000m"
  volumes:
    # - name: gitea-pvc
    #   persistentVolumeClaim:
    #     claimName: gitea-pvc-gitea-0
    - name: mongo-backup
      persistentVolumeClaim:
        claimName: backup-mongo
  restartPolicy: OnFailure
