// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package giteaclient is a generated GoMock package.
package giteaclient

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockGiteaClient is a mock of GiteaClient interface
type MockGiteaClient struct {
	ctrl     *gomock.Controller
	recorder *MockGiteaClientMockRecorder
}

// MockGiteaClientMockRecorder is the mock recorder for MockGiteaClient
type MockGiteaClientMockRecorder struct {
	mock *MockGiteaClient
}

// NewMockGiteaClient creates a new mock instance
func NewMockGiteaClient(ctrl *gomock.Controller) *MockGiteaClient {
	mock := &MockGiteaClient{ctrl: ctrl}
	mock.recorder = &MockGiteaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGiteaClient) EXPECT() *MockGiteaClientMockRecorder {
	return m.recorder
}

// CreateUser mocks base method
func (m *MockGiteaClient) CreateUser(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser
func (mr *MockGiteaClientMockRecorder) CreateUser(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGiteaClient)(nil).CreateUser), email)
}
