{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: gitea
  {{- with .Values.gitea.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - gitea.{{ .Values.domain }}
      secretName: {{ include "tlsSecretName" . }}
  {{- end }}
  rules:
    - host: gitea.{{ .Values.domain }}
      http:
        paths:
          {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: gitea
                port:
                  number: 80
          {{- else }}
          - path: /
            backend:
              serviceName: gitea
              servicePort: http
          {{- end }}
