apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
  labels:
    app:  gitea
spec:
  serviceName: "gitea"
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
      annotations:
        helm.sh/restart-deployment: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: gitea
          image: {{ .Values.gitea.image.repository }}:{{ .Values.gitea.image.tag }}
          imagePullPolicy: {{ .Values.gitea.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: gitea-config
            - secretRef:
                name: postgres
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/su"
                  - "git"
                  - "-c"
                  - "/usr/local/bin/create-admin.sh"
          volumeMounts:
            - name: gitea-pvc
              mountPath: /data
            - name: gitea-init
              mountPath: /data/gitea/conf/app.ini
              subPath: app.ini
            - name: gitea-init
              mountPath: /usr/local/bin/create-admin.sh
              subPath: create-admin.sh
            {{- if and .Values.global.ingress.tls.enabled .Values.global.ingress.tls.caSecret }}
            - mountPath: /etc/ssl/certs/ca-cert.pem
              name: ca-cert
              subPath: {{ .Values.global.ingress.tls.caSecret.certFilename }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 60
    {{- with .Values.gitea.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.gitea.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.gitea.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: gitea-init
          configMap:
            name: gitea-init
            defaultMode: 0777
        {{- if and .Values.global.ingress.tls.enabled .Values.global.ingress.tls.caSecret }}
        - name: ca-cert
          secret:
            secretName: {{ .Values.global.ingress.tls.caSecret.name }}
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: gitea-pvc
        labels:
          app: gitea
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.gitea.storage.storageClassName }}
        resources:
          requests:
            storage:  {{ .Values.gitea.storage.size }}
