// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package configmap is a generated GoMock package.
package configmap

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// WatchConfigMapTemplates mocks base method.
func (m *MockUseCase) WatchConfigMapTemplates(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchConfigMapTemplates", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// WatchConfigMapTemplates indicates an expected call of WatchConfigMapTemplates.
func (mr *MockUseCaseMockRecorder) WatchConfigMapTemplates(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchConfigMapTemplates", reflect.TypeOf((*MockUseCase)(nil).WatchConfigMapTemplates), ctx)
}
