{{- if and .Values.filebrowser.enabled .Values.filebrowser.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kdl-project.filebrowser.name" . }}
  labels:
    {{- include "kdl-project.filebrowserLabels" . | nindent 4 }}
spec:
  {{- if and (not .Values.filebrowser.networkPolicy.policyTypes) (not .Values.filebrowser.networkPolicy.ingress) (not .Values.filebrowser.networkPolicy.egress) }}
  podSelector: {}
  {{- else }}
  podSelector:
    matchLabels:
      {{- include "kdl-project.selectorFilebrowserLabels" . | nindent 6 }}
  {{- end }}

  {{- if .Values.filebrowser.networkPolicy.policyTypes }}
  {{- with .Values.filebrowser.networkPolicy.policyTypes }}
  policyTypes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  policyTypes:
    - Ingress
    - Egress
  {{- end }}

  {{- if .Values.filebrowser.networkPolicy.ingress }}
  {{- with .Values.filebrowser.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  ingress:
  - {}
  {{- end }}

  {{- if .Values.filebrowser.networkPolicy.egress }}
  {{- with .Values.filebrowser.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  egress:
  - {}
  {{- end }}

{{- end }}
