{{- if and .Values.filebrowser.enabled .Values.filebrowser.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kdl-project.filebrowser.name" . }}
  labels:
    {{- include "kdl-project.filebrowserLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kdl-project.selectorFilebrowserLabels" . | nindent 6 }}
  {{- if .Values.filebrowser.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.filebrowser.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.filebrowser.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.filebrowser.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
