{{- if and .Values.filebrowser.enabled .Values.filebrowser.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kdl-project.filebrowserServiceAccountName" . }}
  labels:
    {{- include "kdl-project.filebrowserLabels" . | nindent 4 }}
  {{- with .Values.filebrowser.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.filebrowser.serviceAccount.automount | default "false" }}
{{- end }}
