{{- if and .Values.filebrowser.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kdl-project.filebrowser.name" . }}
  labels:
    {{- include "kdl-project.filebrowserLabels" . | nindent 4 }}
spec:
  type: {{ .Values.filebrowser.service.type }}
  ports:
    - port: {{ .Values.filebrowser.service.port }}
      targetPort: {{ .Values.filebrowser.env.FB_PORT | default (int .Values.filebrowser.service.targetPort | default .Values.filebrowser.service.port) }}
      protocol: TCP
      name: http
      {{- if and (eq "NodePort" .Values.filebrowser.service.type) .Values.filebrowser.service.nodePort }}
      nodePort: {{ .Values.filebrowser.service.nodePort }}
      {{- end }}
    {{- range $port := .Values.filebrowser.service.extraPorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "kdl-project.selectorFilebrowserLabels" . | nindent 4 }}
{{- end }}
