{{- if not .Values.persistentVolume.keepPVC }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kdl-user-tools.fullname" . }}-pvc-cleaner
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
  - kind: ServiceAccount
    name: {{ include "kdl-user-tools.fullname" . }}-pvc-cleaner
roleRef:
  kind: Role
  name: {{ include "kdl-user-tools.fullname" . }}-pvc-cleaner
  apiGroup: rbac.authorization.k8s.io
{{- end }}
