{{- if not .Values.persistentVolume.keepPVC }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kdl-user-tools.fullname" . }}-pvc-cleaner
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "kdl-user-tools.labels" . | nindent 4 }}
{{- end }}
