apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.usernameSlug }}-service-account
subjects:
- kind: ServiceAccount
  name: {{ .Values.usernameSlug }}-service-account
roleRef:
  kind: Role
  name: {{ .Values.usernameSlug }}-service-account
  apiGroup: rbac.authorization.k8s.io
