apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kdl-user-tools.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kdl-user-tools.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kdl-user-tools.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
