FROM python:3.9.1-slim-buster

# Maintainer of the Dockerfile
LABEL maintainer "Intelygenz - Konstellation Team"

# Input data
ENV DEBIAN_FRONTEND=noninteractive \
        TZ=Europe/Madrid \
        NB_GID="1000" \
        NB_UID="1000" \
        NB_USER="jovyan"

ARG VERSION=2.5.0

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Switch to ROOT user to do maintenance tasks
USER root

# Set workdir to tmp
WORKDIR /tmp

# Create a non-root user && clean up && create /run/sshd
RUN groupadd ${NB_USER} --gid ${NB_GID} && \
        useradd ${NB_USER} --system --create-home --uid ${NB_UID} --gid ${NB_GID} --shell /bin/bash && \
        chown -R ${NB_USER}:${NB_GID} /home/${NB_USER} && \
        echo "cat /etc/motd; echo" >> /etc/bash.bashrc

# Install OS dependencies required for the kernel-wrapper. Missing
# packages can be installed later only if container is running as
# privileged user.
RUN apt-get update && apt-get install -yq --no-install-recommends \
    build-essential \
    libsm6 \
    libxext-dev \
    libxrender1 \
    netcat \
    python3-dev \
    tzdata \
    unzip

# Install any packages required for the kernel-wrapper.  If the image
# does not contain the target kernel (i.e., IPython, IRkernel, etc.,
# it should be installed as well.
RUN pip install pycrypto future

# Download and extract the enterprise gateway kernel launchers and bootstrap
# files and deploy to /usr/local/bin. Change permissions to NB_UID:NB_GID.
RUN curl -L https://github.com/jupyter/enterprise_gateway/releases/download/v${VERSION}/jupyter_enterprise_gateway_kernel_image_files-${VERSION}.tar.gz | \
    tar -xz -C /usr/local/bin && \
    chown jovyan:users /usr/local/bin/bootstrap-kernel.sh && \
    chmod 0755 /usr/local/bin/bootstrap-kernel.sh && \
    chown -R jovyan:users /usr/local/bin/kernel-launchers

# Clean up
RUN rm --recursive --force -- /tmp/* && \
        apt-get clean && apt-get autoremove -y && \
        rm -rf /var/lib/{apt,dpkg,cache,log}/

USER jovyan

# Set workdir to user home
# WORKDIR /home/${NB_USER}

ENV KERNEL_LANGUAGE python

CMD /usr/local/bin/bootstrap-kernel.sh