apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kdlprojects.project.konstellation.io
spec:
  group: project.konstellation.io
  names:
    kind: KDLProject
    listKind: KDLProjectList
    plural: kdlprojects
    singular: kdlproject
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: KDLProject is the Schema for the kdlprojects API
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of KDLProject
            type: object
            properties:
              domain:
                description: domain name
                type: string
              giteaOauth2Setup:
                type: object
                properties:
                  image:
                    type: object
                    properties:
                      repository:
                        description: image repository
                        type: string
                      tag:
                        description: image tag
                        type: string
                      pullPolicy:
                        description: image pull policy
                        type: string
              ingress:
                type: object
                properties:
                  type:
                    description: ingress type
                    type: string
              minio:
                type: object
                properties:
                  accessKey:
                    description: minio credentials
                    type: string
                  secretKey:
                    description: minio credentials
                    type: string
              mlflow:
                type: object
                properties:
                  image:
                    type: object
                    properties:
                      repository:
                        description: image repository
                        type: string
                      tag:
                        description: image tag
                        type: string
                      pullPolicy:
                        description: image pull policy
                        type: string
                  s3:
                    type: object
                    properties:
                      bucket:
                        description: minio s3 path
                        type: string
                  volume:
                    type: object
                    properties:
                      size:
                        description: minio volume size
                        type: string
                      storageClassName:
                        description: minio storage class
                        type: string
              oauth2Proxy:
                type: object
                properties:
                  cookieSecret:
                    description: cookie used to authorize
                    type: string
                  image:
                    type: object
                    properties:
                      repository:
                        description: image repository
                        type: string
                      tag:
                        description: image tag
                        type: string
                      pullPolicy:
                        description: image pull policy
                        type: string
              projectId:
                description: Project's ID
                type: string
              sharedVolume:
                type: object
                properties:
                  name:
                    description: ingress type
                    type: string
              tls:
                type: object
                properties:
                  enabled:
                    description: Boolean to specify if TLS is enabled
                    type: string
          status:
            description: Status defines the observed state of KDLProject
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
