apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-tools-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-tools-operator
  template:
    metadata:
      labels:
        name: user-tools-operator
    spec:
      serviceAccountName: user-tools-operator
      containers:
        - name: user-tools-operator
          # Replace this with the built image name
          image: "{{ .Values.userToolsOperator.image.repository }}:{{ .Values.userToolsOperator.image.tag }}"
          imagePullPolicy: {{ .Values.userToolsOperator.image.pullPolicy }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "user-tools-operator"
    {{- with .Values.userToolsOperator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.userToolsOperator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.userToolsOperator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
