{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: minio
  {{- with .Values.minio.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - minio.{{ .Values.domain }}
      secretName: {{ include "tlsSecretName" . }}
  {{- end }}
  rules:
    - host: minio.{{ .Values.domain }}
      http:
        paths:
          {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Release.Name }}-minio
                port:
                  number: 9000
          {{- else }}
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-minio
              servicePort: 9000
          {{- end }}
