{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: minio-console
  {{- with .Values.minio.consoleIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  {{- if .Values.minio.consoleIngress.className }}
  ingressClassName: {{ .Values.minio.consoleIngress.className }}
  {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        - minio-console.{{ .Values.global.domain }}
      secretName: {{ include "minioConsole.tlsSecretName" . }}
  {{- end }}
  rules:
    - host: minio-console.{{ .Values.global.domain }}
      http:
        paths:
          - path: "/"
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ .Release.Name }}-minio-console
                port:
                  number: 9001
              {{- else }}
              serviceName: {{ .Release.Name }}-minio-console
              servicePort: 9001
              {{- end }}
