// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package capabilities is a generated GoMock package.
package capabilities

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/konstellation-io/kdl-server/app/api/entity"
	model "github.com/konstellation-io/kdl-server/app/api/infrastructure/graph/model"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockRepository) FindAll(ctx context.Context) ([]entity.Capabilities, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]entity.Capabilities)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRepositoryMockRecorder) FindAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRepository)(nil).FindAll), ctx)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, id string) (entity.Capabilities, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(entity.Capabilities)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, id)
}

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetCapabilities mocks base method.
func (m *MockUseCase) GetCapabilities(ctx context.Context) ([]model.Capability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCapabilities", ctx)
	ret0, _ := ret[0].([]model.Capability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCapabilities indicates an expected call of GetCapabilities.
func (mr *MockUseCaseMockRecorder) GetCapabilities(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCapabilities", reflect.TypeOf((*MockUseCase)(nil).GetCapabilities), ctx)
}

// GetRunningCapability mocks base method.
func (m *MockUseCase) GetRunningCapability(ctx context.Context, username string) (*model.Capability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunningCapability", ctx, username)
	ret0, _ := ret[0].(*model.Capability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunningCapability indicates an expected call of GetRunningCapability.
func (mr *MockUseCaseMockRecorder) GetRunningCapability(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunningCapability", reflect.TypeOf((*MockUseCase)(nil).GetRunningCapability), ctx, username)
}
