"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc

import grpc

from proto.knowledge_graph_pb2 import *


class KGServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    def GetGraph(self,
        request: global___GetGraphReq,
    ) -> global___GetGraphRes: ...

    def GetItem(self,
        request: global___GetItemReq,
    ) -> global___GetItemRes: ...

    def GetDescriptionQuality(self,
        request: global___DescriptionQualityReq,
    ) -> global___DescriptionQualityRes: ...


class KGServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetGraph(self,
        request: global___GetGraphReq,
        context: grpc.ServicerContext,
    ) -> global___GetGraphRes: ...

    @abc.abstractmethod
    def GetItem(self,
        request: global___GetItemReq,
        context: grpc.ServicerContext,
    ) -> global___GetItemRes: ...

    @abc.abstractmethod
    def GetDescriptionQuality(self,
        request: global___DescriptionQualityReq,
        context: grpc.ServicerContext,
    ) -> global___DescriptionQualityRes: ...


def add_KGServiceServicer_to_server(servicer: KGServiceServicer, server: grpc.Server) -> None: ...
