"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc

from .knowledge_graph_pb2 import *
class KGServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    def GetGraph(self,
        request: global___GetGraphReq,
    ) -> global___GetGraphRes: ...


class KGServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetGraph(self,
        request: global___GetGraphReq,
        context: grpc.ServicerContext,
    ) -> global___GetGraphRes: ...


def add_KGServiceServicer_to_server(servicer: KGServiceServicer, server: grpc.Server) -> None: ...
