# Docker linter https://github.com/hadolint/hadolint
# # https://github.com/hadolint/hadolint#rules

failure-threshold: info

label-schema:
  maintainer: text

override:
  warning:
    - DL3049
  info:
    - DL3008
