{{ if .Values.knowledgeGalaxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: knowledge-galaxy-configmap
  labels:
    app:  knowledge-galaxy-configmap
data:
  WORKERS: "{{ .Values.knowledgeGalaxy.workers }}" # Number of threads for the server defaults to 1
  HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  # Recommender Settings
  N_HITS: "{{ .Values.knowledgeGalaxy.numberOfOutputs }}" # Number of outputs that the recommender outputs, defaults to 10
  DESCRIPTION_MIN_WORDS: "{{ .Values.knowledgeGalaxy.descriptionMinWords }}" # Number of words to use for project description, defaults to 10
  # Log file
  LOG_LEVEL: "{{ .Values.knowledgeGalaxy.logLevel }}" # Log level defaults to info
  STANDALONE_MODE: "false"

  config.json: |+
    {
      "SERVER_NAME": "{{ .Values.serverName }}",
      "SERVER_URL": "{{ include "protocol" . }}://kdlapp.{{ .Values.domain }}/kg",
      "MODE": "iframe",
      "BASENAME": "/kg/",
      "DESCRIPTION_MIN_WORDS": "{{ .Values.knowledgeGalaxy.descriptionMinWords }}"
    }
{{ end }}
