{{ if .Values.knowledgeGalaxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-galaxy
spec:
  selector:
    matchLabels:
      app: knowledge-galaxy
  template:
    metadata:
      labels:
        app: knowledge-galaxy
      annotations:
        helm.sh/restart-deployment: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: knowledge-galaxy
          image: {{ .Values.knowledgeGalaxy.image.repository }}:{{ .Values.knowledgeGalaxy.image.tag }}
          imagePullPolicy: {{ .Values.knowledgeGalaxy.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: knowledge-galaxy-configmap
            - secretRef:
                name: knowledge-galaxy-secrets
          volumeMounts:
            - name: knowledge-galaxy-configmap
              mountPath: /kg/public/config.json
              subPath: config.json
          ports:
            - containerPort: 8080
      volumes:
        - name: knowledge-galaxy-configmap
          configMap:
            name: knowledge-galaxy-configmap
{{ end }}
