{{ if .Values.knowledgeGalaxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-galaxy
spec:
  selector:
    matchLabels:
      app: knowledge-galaxy
  template:
    metadata:
      labels:
        app: knowledge-galaxy
      annotations:
        checksum/env-config: {{ include (print $.Template.BasePath "/knowledge-galaxy/env-config.yaml") . | sha256sum }}
        checksum/ui-config: {{ include (print $.Template.BasePath "/knowledge-galaxy/env-config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/knowledge-galaxy/secret.yaml") . | sha256sum }}
    spec:
      {{- if .Values.knowledgeGalaxy.serviceaccount.enabled }}
      serviceAccountName:  {{ template "knowledgeGalaxy.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: knowledge-galaxy
          image: {{ .Values.knowledgeGalaxy.image.repository }}:{{ .Values.knowledgeGalaxy.image.tag }}
          imagePullPolicy: {{ .Values.knowledgeGalaxy.image.pullPolicy }}
          env:
            - name: SERVER_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.mongodb.connectionString.secretName }}
                  key: {{ .Values.global.mongodb.connectionString.secretKey }}
          envFrom:
            - configMapRef:
                name: knowledge-galaxy-env
          volumeMounts:
            - name: config
              mountPath: /kg/public/config.json
              subPath: config.json
          ports:
            - containerPort: 8080
    {{- with .Values.knowledgeGalaxy.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.knowledgeGalaxy.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.knowledgeGalaxy.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: knowledge-galaxy-ui
{{ end }}
