{{ if .Values.knowledgeGalaxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: knowledge-galaxy
  labels:
    app: knowledge-galaxy
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: knowledge-galaxy
{{ end }}
