{{ if .Values.knowledgeGalaxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: knowledge-galaxy-ui
  labels:
    app:  knowledge-galaxy
data:
  config.json: |+
    {
      "SERVER_NAME": "{{ .Values.global.serverName }}",
      "SERVER_URL": "{{ include "http.protocol" . }}://kdlapp.{{ .Values.global.domain }}/kg",
      "MODE": "iframe",
      "BASENAME": "/kg/",
      "DESCRIPTION_MIN_WORDS": {{ default "50" .Values.knowledgeGalaxy.config.descriptionMinWords }}
    }
{{ end }}
