{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "user-tools.fullname" . }}
  labels:
{{ include "user-tools.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.usernameSlug }}-code.{{ .Values.domain }}
      secretName: {{ include "user-tools.tlsSecretName" . }}
  {{- end }}
  rules:
    - host: {{ .Values.usernameSlug }}-code.{{ .Values.domain }}
      http:
        paths:
          {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "user-tools.fullname" . }}-code
                port:
                  number: 80
          {{- else }}
          - path: /
            backend:
              serviceName: {{ include "user-tools.fullname" . }}-code
              servicePort: http
          {{- end }}
