{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ include "user-tools.fullname" . }}
  labels:
{{ include "user-tools.labels" . | indent 4 }}
  annotations:
    {{ if eq .Values.ingress.type "nginx" }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "1000000m"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: ALLOW-FROM {{ include "protocol" . }}://kdlapp.{{ .Values.domain }}";
      more_set_headers "Content-Security-Policy: frame-ancestors 'self' {{ include "protocol" . }}://kdlapp.{{ .Values.domain}}";
    {{ end }}
spec:
  {{ if .Values.tls -}}
  tls:
    - hosts:
        - {{ .Values.usernameSlug }}-code.{{ .Values.domain }}
        - {{ .Values.usernameSlug }}-jupyter.{{ .Values.domain }}
      secretName: {{ .Values.domain }}-tls-secret
  {{- end }}
  rules:
    - host: {{ .Values.usernameSlug }}-code.{{ .Values.domain }}
      http:
        paths:
          {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "user-tools.fullname" . }}-code
                port:
                  number: 80
          {{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
          - path: /
            backend:
              serviceName: {{ include "user-tools.fullname" . }}-code
              servicePort: http
          {{ end }} 
    - host: {{ .Values.usernameSlug }}-jupyter.{{ .Values.domain }}
      http:
        paths:
          {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "user-tools.fullname" . }}-jupyter
                port:
                  number: 80
          {{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
          - path: /
            backend:
              serviceName: {{ include "user-tools.fullname" . }}-jupyter
              servicePort: http
          {{ end }} 
