apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-tools.fullname" . }}-oauth2-proxy
data:
  oauth2_proxy.cfg: |+
    provider="github"
    login_url="{{ printf "%s://gitea.%s/login/oauth/authorize" ( include "protocol" . ) .Values.domain }}"
    redeem_url="{{ printf "%s://gitea.%s/login/oauth/access_token" ( include "protocol" . ) .Values.domain }}"
    validate_url="{{ printf "%s://gitea.%s/api/v1" ( include "protocol" . ) .Values.domain }}"
    profile_url="{{ printf "%s://gitea.%s/api/v1/user" ( include "protocol" . ) .Values.domain }}"
    cookie_secret="p0aw4r65890a3vnl"
    cookie_secure={{ .Values.tls }}
    cookie_samesite="none"
    ssl_insecure_skip_verify=true
    ssl_upstream_insecure_skip_verify=true
