apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: user-tools-{{ .Values.usernameSlug }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/exec
  resourceNames:
  - "{{ include "user-tools.fullname" . }}-0"
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - delete
