{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: drone
  {{- with .Values.drone.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app:  drone
spec:
  {{- if .Values.drone.ingress.className }}
  ingressClassName: {{ .Values.drone.ingress.className }}
  {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        - drone.{{ .Values.global.domain }}
      secretName: {{ include "drone.tlsSecretName" . }}
  {{- end }}
  rules:
    - host: drone.{{ .Values.global.domain }}
      http:
        paths:
        - path: "/"
          {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
          pathType: Prefix
          {{- end }}
          backend:
            {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
            service:
              name: drone
              port:
                number: 80
            {{- else }}
            serviceName: drone
            servicePort: http
            {{- end }}
