{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: drone
  annotations:
    {{ if eq .Values.ingress.type "nginx" }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: ALLOW-FROM {{ include "protocol" . }}://kdlapp.{{ .Values.domain }}";
      more_set_headers "Content-Security-Policy: frame-ancestors 'self' {{ include "protocol" . }}://kdlapp.{{ .Values.domain}}";
    {{ end }}
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  labels:
    app:  drone
spec:
  {{ if .Values.tls.enabled -}}
  tls:
    - hosts:
        - drone.{{ .Values.domain }}
      secretName: {{ include "tlsSecretName" . }}
  {{- end }}
  rules:
    - host: drone.{{ .Values.domain }}
      http:
        paths:
          {{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: drone
                port:
                  number: 80
          {{ else }}
          - path: /
            backend:
              serviceName: drone
              servicePort: http
          {{ end }}
