apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: drone
  labels:
    app:  drone
data:
  DRONE_RPC_SECRET: {{ .Values.drone.rpcSecret | b64enc }}
  DRONE_DATABASE_DATASOURCE: {{ printf "postgres://postgres:%s@postgres:5432/drone?sslmode=disable" .Values.postgres.dbPassword | b64enc }}
  DRONE_USER_CREATE: {{ printf "username:%s,admin:true,token:%s" .Values.gitea.admin.username .Values.drone.adminToken | b64enc }}
