apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drone
  labels:
    app:  drone
spec:
  serviceName: "drone"
  replicas: 1
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/drone/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/drone/secret.yaml") . | sha256sum }}
        checksum/oauth2-secret: {{ include (print $.Template.BasePath "/drone/oauth2-secret.yaml") . | sha256sum }}
        checksum/gitea-oauth2-config: {{ include (print $.Template.BasePath "/common/gitea-oauth2-configmap.yaml") . | sha256sum }}
        checksum/gitea-admin-secret: {{ include (print $.Template.BasePath "/common/gitea-admin-secret.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: gitea-oauth2-setup
          image: {{ .Values.giteaOauth2Setup.image.repository }}:{{ .Values.giteaOauth2Setup.image.tag }}
          imagePullPolicy: {{ .Values.giteaOauth2Setup.image.pullPolicy }}
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: gitea-admin
            - secretRef:
                name: drone-oauth2
            - configMapRef:
                name: gitea-oauth2
      containers:
        - name: drone
          image: {{ .Values.drone.image.repository }}:{{ .Values.drone.image.tag }}
          imagePullPolicy: {{ .Values.drone.image.pullPolicy }}
          env:
            - name: DRONE_GITEA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  # App generated secret
                  name: drone-oauth2-credentials
                  key: OAUTH2_CLIENT_ID
            - name: DRONE_GITEA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  # App generated secret
                  name: drone-oauth2-credentials
                  key: OAUTH2_CLIENT_SECRET
          envFrom:
            - configMapRef:
                name: drone
            - secretRef:
                name: drone
          volumeMounts:
            - name: drone-pvc
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
    {{- with .Values.drone.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.drone.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.drone.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: drone-pvc
        labels:
          app: drone
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.drone.storage.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.drone.storage.size }}
