{{ if .Capabilities.APIVersions.Has "apps/v1" }}
apiVersion: apps/v1
{{ else if .Capabilities.APIVersions.Has "apps/v1beta1" }}
apiVersion: apps/v1beta1
{{ end }}
kind: StatefulSet
metadata:
  name: drone
  labels:
    app:  drone
spec:
  serviceName: "drone"
  replicas: 1
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
      annotations:
        helm.sh/restart-deployment: {{ randAlphaNum 5 | quote }} # TODO
    spec:
      initContainers:
        - name: gitea-oauth2-setup
          image: {{ .Values.giteaOauth2Setup.image.repository }}:{{ .Values.giteaOauth2Setup.image.tag }}
          imagePullPolicy: {{ .Values.giteaOauth2Setup.image.pullPolicy }}
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: gitea-admin-secrets
            - secretRef:
                name: drone-oauth2-secrets
            - configMapRef:
                name: gitea-configmap
      containers:
        - name: drone
          image: {{ .Values.drone.image.repository }}:{{ .Values.drone.image.tag }}
          imagePullPolicy: {{ .Values.drone.image.pullPolicy }}
          env:
            - name: DRONE_GITEA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: drone-oauth2-credentials
                  key: OAUTH2_CLIENT_ID
            - name: DRONE_GITEA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-oauth2-credentials
                  key: OAUTH2_CLIENT_SECRET
          envFrom:
            - configMapRef:
                name: drone-config
            - secretRef:
                name: drone-oauth2-secrets
          volumeMounts:
            - name: drone-pvc
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
    {{- with .Values.drone.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.drone.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.drone.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: drone-pvc
        labels:
          app: drone
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.drone.storage.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.drone.storage.size }}
