// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package kgservice is a generated GoMock package.
package kgservice

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/konstellation-io/kdl-server/app/api/entity"
)

// MockKGService is a mock of KGService interface.
type MockKGService struct {
	ctrl     *gomock.Controller
	recorder *MockKGServiceMockRecorder
}

// MockKGServiceMockRecorder is the mock recorder for MockKGService.
type MockKGServiceMockRecorder struct {
	mock *MockKGService
}

// NewMockKGService creates a new mock instance.
func NewMockKGService(ctrl *gomock.Controller) *MockKGService {
	mock := &MockKGService{ctrl: ctrl}
	mock.recorder = &MockKGServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKGService) EXPECT() *MockKGServiceMockRecorder {
	return m.recorder
}

// GetGraph mocks base method.
func (m *MockKGService) GetGraph(ctx context.Context, description string) (entity.KnowledgeGraph, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGraph", ctx, description)
	ret0, _ := ret[0].(entity.KnowledgeGraph)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGraph indicates an expected call of GetGraph.
func (mr *MockKGServiceMockRecorder) GetGraph(ctx, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGraph", reflect.TypeOf((*MockKGService)(nil).GetGraph), ctx, description)
}

// GetItem mocks base method.
func (m *MockKGService) GetItem(ctx context.Context, id string) (entity.KnowledgeGraphItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", ctx, id)
	ret0, _ := ret[0].(entity.KnowledgeGraphItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockKGServiceMockRecorder) GetItem(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockKGService)(nil).GetItem), ctx, id)
}

// DescriptionQuality mocks base method
func (m *MockKGService) DescriptionQuality(ctx context.Context, description string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescriptionQuality", ctx, description)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescriptionQuality indicates an expected call of DescriptionQuality
func (mr *MockKGServiceMockRecorder) DescriptionQuality(ctx, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescriptionQuality", reflect.TypeOf((*MockKGService)(nil).DescriptionQuality), ctx, description)
}
