{{- if and .Values.mlflow.enabled .Values.mlflow.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kdl-project.mlflow.name" . }}
  labels:
    {{- include "kdl-project.mlflowLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kdl-project.mlflow.name" . }}
  minReplicas: {{ .Values.mlflow.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.mlflow.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.mlflow.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.mlflow.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.mlflow.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.mlflow.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
