{{- if and .Values.mlflow.enabled .Values.mlflow.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kdl-project.mlflowServiceAccountName" . }}
  labels:
    {{- include "kdl-project.mlflowLabels" . | nindent 4 }}
  {{- with .Values.mlflow.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.mlflow.serviceAccount.automount | default "false" }}
{{- end }}
