apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  members: {{ .Values.mongodb.replicaset.members }}
  type: ReplicaSet
  version: {{ .Values.mongodb.version }}
  security:
    authentication:
      modes: ["SCRAM"]
    roles:
    - role: readWriteMinusDropRole
      db: kdl
      privileges:
      - resource:
          db: kdl
          collection: ""
        actions:
        - collStats
        - dbHash
        - dbStats
        - find
        - killCursors
        - listIndexes
        - listCollections
        - convertToCapped
        - createCollection
        - createIndex
        - dropIndex
        - insert
        - remove
        - renameCollectionSameDB
        - update
      roles: []
  users:
  - name: admin
    db: admin
    passwordSecretRef:
      name: kdl-mongo-secret
      key: MONGO_INITDB_ROOT_PASSWORD
    roles:
    - name: root
      db: admin
    - name: readWriteMinusDropRole
      db: kdl
    scramCredentialsSecretName: {{ .Release.Name }}-mongodb-admin
  statefulSet:
    spec:
      template:
        spec:
          volumes:
          - name: old-mongo-pvc
            persistentVolumeClaim:
              claimName: kdl-local-mongo-pvc-kdl-mongo-0
          containers:
          - name: mongod
            volumeMounts:
            - name: old-mongo-pvc
              mountPath: "/data/db"
