apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.projectId }}-mlflow-config
  labels:
    app:  {{ .Values.projectId }}-mlflow-config
data:
  ARTIFACTS_BUCKET: {{ .Values.mlflow.s3.bucket }}
  MLFLOW_S3_ENDPOINT_URL: {{ .Values.minio.endpointURL }}
