apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.projectId }}-mlflow-config
  labels:
    app:  {{ .Values.projectId }}-mlflow-config
data:
  MLFLOW_S3_ENDPOINT_URL: http://{{.Release.Name }}-minio:9000
  ARTIFACTS_BUCKET: {{ .Values.mlflow.s3.bucket }}
