apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.projectId }}-mlflow
  labels:
    app: {{ .Values.projectId }}-mlflow
  {{- with .Values.mlflow.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.mlflow.ingress.className }}
  ingressClassName: {{ .Values.mlflow.ingress.className }}
  {{- end }}
  {{- if .Values.mlflow.ingress.tls.enabled }}
  tls:
  - hosts:
      - {{ .Values.projectId }}-mlflow.{{ .Values.domain }}
    secretName: {{ include "kdlproject.mlflow.tlsSecretName" . }}
  {{- end }}
  rules: 
  - host: {{ .Values.projectId }}-mlflow.{{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.projectId }}-mlflow
            port:
              number: 5000
