apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.projectId }}-mlflow-oauth2-secrets
type: Opaque
data:
  DEPLOYMENT_SECRET_NAME: {{ printf "%s-mlflow-oauth2-credentials" .Values.projectId | b64enc }}
  GITEA_REDIRECT_URIS: {{ printf "%s://%s-mlflow.%s/oauth2/callback" ( include "protocol" . ) .Values.projectId .Values.domain | b64enc }}
  GITEA_APPLICATION_NAME: {{ printf "%s-mlflow" .Values.projectId | b64enc }}
