kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.projectId }}-mlflow-claim
spec:
  storageClassName: {{ .Values.mlflow.volume.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mlflow.volume.size }}
