apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.projectId }}-mlflow-secret
  labels:
    app:  {{ .Values.projectId }}-mlflow-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secretKey | b64enc }}
  MLFLOW_S3_ENDPOINT_URL: {{ .Values.minio.endpointURL | b64enc }}
