apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.projectId }}-mlflow
  labels:
    app: {{ .Values.projectId }}-mlflow
spec:
  clusterIP: None
  ports:
    - name: internal
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: {{ .Values.projectId }}-mlflow
