{{ if .Values.backup.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
  labels:
    app: backup
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 2
  startingDeadlineSeconds: 60 # 1min
  jobTemplate:
    metadata:
      name: {{ .Values.backup.name }}
    spec:
      backoffLimit: {{ .Values.backup.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.backup.activeDeadlineSeconds }}
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          containers:
            - name: {{ .Values.backup.name }}
              image: {{ .Values.backup.image.repository }}:{{ .Values.backup.image.tag }}
              imagePullPolicy: {{ .Values.backup.image.pullPolicy }}
              securityContext:
                allowPrivilegeEscalation: false
              resources:
                limits:
                  memory: {{ .Values.backup.resources.limits.memory }}
                  cpu: {{ .Values.backup.resources.limits.cpu }}
                requests:
                  memory: {{ .Values.backup.resources.requests.memory }}
                  cpu: {{ .Values.backup.resources.requests.cpu }}
              envFrom:
                - secretRef:
                    name: postgres
                - secretRef:
                    name: backup
              env:
                - name: MONGO_URI
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.global.mongodb.connectionString.secretName }}
                      key: {{ .Values.global.mongodb.connectionString.secretKey }}
              volumeMounts:
              - name: gitea-pvc
                mountPath: "/data"
            {{- with .Values.backup.extraVolumeMounts }}
{{ toYaml . | indent 14 }}
            {{- end }}
          volumes:
            - name: gitea-pvc
              persistentVolumeClaim:
                claimName: gitea-pvc-gitea-0
            {{- with .Values.backup.extraVolumes }}
{{ toYaml . | indent 12 }}
            {{- end }}
          restartPolicy: OnFailure
{{- end }}
