apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-galaxy
spec:
  selector:
    matchLabels:
      app: knowledge-galaxy
  template:
    metadata:
      labels:
        app: knowledge-galaxy
      annotations:
        helm.sh/restart-deployment: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: knowledge-galaxy
          image: {{ .Values.kdlKG.image.repository }}:{{ .Values.kdlKG.image.tag }}
          imagePullPolicy: {{ .Values.kdlKG.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: knowledge-galaxy-configmap
          ports:
            - containerPort: {{ .Values.kdlKG.port }}
