apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdl-kg
spec:
  selector:
    matchLabels:
      app: kdl-kg
  template:
    metadata:
      labels:
        app: kdl-kg
      annotations:
        helm.sh/restart-deployment: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: kdl-kg
          image: {{ .Values.docker.registry }}{{ .Values.kdlKG.image.repository }}:{{ .Values.kdlKG.image.tag }}
          imagePullPolicy: {{ .Values.kdlKG.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: kdl-kg-configmap
          ports:
            - containerPort: {{ .Values.kdlKG.port }}
