apiVersion: v1
kind: Secret
metadata:
  name: kdl-kg-s3-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.kdlKG.s3.keyID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.kdlKG.s3.keySecret | b64enc }}
  BUCKET_NAME: {{ .Values.kdlKG.bucketName | b64enc }}