apiVersion: v1
kind: Service
metadata:
  name: kdl-kg
  labels:
    app: kdl-kg
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: {{ .Values.kdlKG.port }}
      protocol: TCP
      name: http
  selector:
    app: kdl-kg
