apiVersion: v1
kind: Service
metadata:
  name: knowledge-galaxy
  labels:
    app: knowledge-galaxy
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: {{ .Values.kdlKG.port }}
      protocol: TCP
      name: http
  selector:
    app: knowledge-galaxy
