// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: proto/knowledge_graph.proto

package kgpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetGraphReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *GetGraphReq) Reset() {
	*x = GetGraphReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_knowledge_graph_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGraphReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphReq) ProtoMessage() {}

func (x *GetGraphReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_graph_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphReq.ProtoReflect.Descriptor instead.
func (*GetGraphReq) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_graph_proto_rawDescGZIP(), []int{0}
}

func (x *GetGraphReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GraphItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category   string  `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Title      string  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Abstract   string  `protobuf:"bytes,4,opt,name=abstract,proto3" json:"abstract,omitempty"`
	Authors    string  `protobuf:"bytes,5,opt,name=authors,proto3" json:"authors,omitempty"`
	Score      float32 `protobuf:"fixed32,6,opt,name=score,proto3" json:"score,omitempty"`
	Date       string  `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Url        string  `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	ExternalId string  `protobuf:"bytes,9,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Framework  string  `protobuf:"bytes,10,opt,name=framework,proto3" json:"framework,omitempty"`
}

func (x *GraphItem) Reset() {
	*x = GraphItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_knowledge_graph_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphItem) ProtoMessage() {}

func (x *GraphItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_graph_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphItem.ProtoReflect.Descriptor instead.
func (*GraphItem) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_graph_proto_rawDescGZIP(), []int{1}
}

func (x *GraphItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GraphItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GraphItem) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

func (x *GraphItem) GetAuthors() string {
	if x != nil {
		return x.Authors
	}
	return ""
}

func (x *GraphItem) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GraphItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GraphItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GraphItem) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *GraphItem) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

type GetGraphRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GraphItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetGraphRes) Reset() {
	*x = GetGraphRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_knowledge_graph_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGraphRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphRes) ProtoMessage() {}

func (x *GetGraphRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_knowledge_graph_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphRes.ProtoReflect.Descriptor instead.
func (*GetGraphRes) Descriptor() ([]byte, []int) {
	return file_proto_knowledge_graph_proto_rawDescGZIP(), []int{2}
}

func (x *GetGraphRes) GetItems() []*GraphItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_knowledge_graph_proto protoreflect.FileDescriptor

var file_proto_knowledge_graph_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x6b,
	0x67, 0x22, 0x2f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x71,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xfe, 0x01, 0x0a, 0x09, 0x47, 0x72, 0x61, 0x70, 0x68, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x22, 0x32, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52,
	0x65, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6b, 0x67, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0x3b, 0x0a, 0x09, 0x4b, 0x47, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68,
	0x12, 0x0f, 0x2e, 0x6b, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65,
	0x71, 0x1a, 0x0f, 0x2e, 0x6b, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x6b, 0x67,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_knowledge_graph_proto_rawDescOnce sync.Once
	file_proto_knowledge_graph_proto_rawDescData = file_proto_knowledge_graph_proto_rawDesc
)

func file_proto_knowledge_graph_proto_rawDescGZIP() []byte {
	file_proto_knowledge_graph_proto_rawDescOnce.Do(func() {
		file_proto_knowledge_graph_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_knowledge_graph_proto_rawDescData)
	})
	return file_proto_knowledge_graph_proto_rawDescData
}

var file_proto_knowledge_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_knowledge_graph_proto_goTypes = []interface{}{
	(*GetGraphReq)(nil), // 0: kg.GetGraphReq
	(*GraphItem)(nil),   // 1: kg.GraphItem
	(*GetGraphRes)(nil), // 2: kg.GetGraphRes
}
var file_proto_knowledge_graph_proto_depIdxs = []int32{
	1, // 0: kg.GetGraphRes.items:type_name -> kg.GraphItem
	0, // 1: kg.KGService.GetGraph:input_type -> kg.GetGraphReq
	2, // 2: kg.KGService.GetGraph:output_type -> kg.GetGraphRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_knowledge_graph_proto_init() }
func file_proto_knowledge_graph_proto_init() {
	if File_proto_knowledge_graph_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_knowledge_graph_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGraphReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_knowledge_graph_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_knowledge_graph_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGraphRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_knowledge_graph_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_knowledge_graph_proto_goTypes,
		DependencyIndexes: file_proto_knowledge_graph_proto_depIdxs,
		MessageInfos:      file_proto_knowledge_graph_proto_msgTypes,
	}.Build()
	File_proto_knowledge_graph_proto = out.File
	file_proto_knowledge_graph_proto_rawDesc = nil
	file_proto_knowledge_graph_proto_goTypes = nil
	file_proto_knowledge_graph_proto_depIdxs = nil
}
