// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package k8s is a generated GoMock package.
package k8s

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/konstellation-io/kdl-server/app/api/entity"
	v1 "k8s.io/api/core/v1"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// CreateKDLProjectCR mocks base method.
func (m *MockClientInterface) CreateKDLProjectCR(ctx context.Context, projectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKDLProjectCR", ctx, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateKDLProjectCR indicates an expected call of CreateKDLProjectCR.
func (mr *MockClientInterfaceMockRecorder) CreateKDLProjectCR(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKDLProjectCR", reflect.TypeOf((*MockClientInterface)(nil).CreateKDLProjectCR), ctx, projectID)
}

// CreateSecret mocks base method.
func (m *MockClientInterface) CreateSecret(ctx context.Context, name string, values, labels map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", ctx, name, values, labels)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockClientInterfaceMockRecorder) CreateSecret(ctx, name, values, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockClientInterface)(nil).CreateSecret), ctx, name, values, labels)
}

// CreateUserSSHKeySecret mocks base method.
func (m *MockClientInterface) CreateUserSSHKeySecret(ctx context.Context, user entity.User, public, private string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserSSHKeySecret", ctx, user, public, private)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserSSHKeySecret indicates an expected call of CreateUserSSHKeySecret.
func (mr *MockClientInterfaceMockRecorder) CreateUserSSHKeySecret(ctx, user, public, private interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserSSHKeySecret", reflect.TypeOf((*MockClientInterface)(nil).CreateUserSSHKeySecret), ctx, user, public, private)
}

// CreateUserServiceAccount mocks base method.
func (m *MockClientInterface) CreateUserServiceAccount(ctx context.Context, usernameSlug string) (*v1.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserServiceAccount", ctx, usernameSlug)
	ret0, _ := ret[0].(*v1.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserServiceAccount indicates an expected call of CreateUserServiceAccount.
func (mr *MockClientInterfaceMockRecorder) CreateUserServiceAccount(ctx, usernameSlug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserServiceAccount", reflect.TypeOf((*MockClientInterface)(nil).CreateUserServiceAccount), ctx, usernameSlug)
}

// CreateUserToolsCR mocks base method.
func (m *MockClientInterface) CreateUserToolsCR(ctx context.Context, username, runtimeID, runtimeImage, runtimeTag string, capabilities entity.Capabilities) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserToolsCR", ctx, username, runtimeID, runtimeImage, runtimeTag, capabilities)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserToolsCR indicates an expected call of CreateUserToolsCR.
func (mr *MockClientInterfaceMockRecorder) CreateUserToolsCR(ctx, username, runtimeID, runtimeImage, runtimeTag, capabilities interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserToolsCR", reflect.TypeOf((*MockClientInterface)(nil).CreateUserToolsCR), ctx, username, runtimeID, runtimeImage, runtimeTag, capabilities)
}

// DeleteKDLProjectCR mocks base method.
func (m *MockClientInterface) DeleteKDLProjectCR(ctx context.Context, projectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKDLProjectCR", ctx, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKDLProjectCR indicates an expected call of DeleteKDLProjectCR.
func (mr *MockClientInterfaceMockRecorder) DeleteKDLProjectCR(ctx, projectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKDLProjectCR", reflect.TypeOf((*MockClientInterface)(nil).DeleteKDLProjectCR), ctx, projectID)
}

// DeleteUserServiceAccount mocks base method.
func (m *MockClientInterface) DeleteUserServiceAccount(ctx context.Context, usernameSlug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserServiceAccount", ctx, usernameSlug)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserServiceAccount indicates an expected call of DeleteUserServiceAccount.
func (mr *MockClientInterfaceMockRecorder) DeleteUserServiceAccount(ctx, usernameSlug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserServiceAccount", reflect.TypeOf((*MockClientInterface)(nil).DeleteUserServiceAccount), ctx, usernameSlug)
}

// DeleteUserToolsCR mocks base method.
func (m *MockClientInterface) DeleteUserToolsCR(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserToolsCR", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserToolsCR indicates an expected call of DeleteUserToolsCR.
func (mr *MockClientInterfaceMockRecorder) DeleteUserToolsCR(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserToolsCR", reflect.TypeOf((*MockClientInterface)(nil).DeleteUserToolsCR), ctx, username)
}

// GetCapabilitiesIDFromUserTools mocks base method.
func (m *MockClientInterface) GetCapabilitiesIDFromUserTools(ctx context.Context, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCapabilitiesIDFromUserTools", ctx, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCapabilitiesIDFromUserTools indicates an expected call of GetCapabilitiesIDFromUserTools.
func (mr *MockClientInterfaceMockRecorder) GetCapabilitiesIDFromUserTools(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCapabilitiesIDFromUserTools", reflect.TypeOf((*MockClientInterface)(nil).GetCapabilitiesIDFromUserTools), ctx, username)
}

// GetConfigMap mocks base method.
func (m *MockClientInterface) GetConfigMap(ctx context.Context, name string) (*v1.ConfigMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigMap", ctx, name)
	ret0, _ := ret[0].(*v1.ConfigMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigMap indicates an expected call of GetConfigMap.
func (mr *MockClientInterfaceMockRecorder) GetConfigMap(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigMap", reflect.TypeOf((*MockClientInterface)(nil).GetConfigMap), ctx, name)
}

// GetRuntimeIDFromUserTools mocks base method.
func (m *MockClientInterface) GetRuntimeIDFromUserTools(ctx context.Context, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRuntimeIDFromUserTools", ctx, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRuntimeIDFromUserTools indicates an expected call of GetRuntimeIDFromUserTools.
func (mr *MockClientInterfaceMockRecorder) GetRuntimeIDFromUserTools(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRuntimeIDFromUserTools", reflect.TypeOf((*MockClientInterface)(nil).GetRuntimeIDFromUserTools), ctx, username)
}

// GetSecret mocks base method.
func (m *MockClientInterface) GetSecret(ctx context.Context, name string) (map[string][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", ctx, name)
	ret0, _ := ret[0].(map[string][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockClientInterfaceMockRecorder) GetSecret(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockClientInterface)(nil).GetSecret), ctx, name)
}

// GetUserKubeconfig mocks base method.
func (m *MockClientInterface) GetUserKubeconfig(ctx context.Context, usernameSlug string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserKubeconfig", ctx, usernameSlug)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserKubeconfig indicates an expected call of GetUserKubeconfig.
func (mr *MockClientInterfaceMockRecorder) GetUserKubeconfig(ctx, usernameSlug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserKubeconfig", reflect.TypeOf((*MockClientInterface)(nil).GetUserKubeconfig), ctx, usernameSlug)
}

// GetUserSSHKeyPublic mocks base method.
func (m *MockClientInterface) GetUserSSHKeyPublic(ctx context.Context, usernameSlug string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSSHKeyPublic", ctx, usernameSlug)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSSHKeyPublic indicates an expected call of GetUserSSHKeyPublic.
func (mr *MockClientInterfaceMockRecorder) GetUserSSHKeyPublic(ctx, usernameSlug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSSHKeyPublic", reflect.TypeOf((*MockClientInterface)(nil).GetUserSSHKeyPublic), ctx, usernameSlug)
}

// GetUserSSHKeySecret mocks base method.
func (m *MockClientInterface) GetUserSSHKeySecret(ctx context.Context, usernameSlug string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSSHKeySecret", ctx, usernameSlug)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSSHKeySecret indicates an expected call of GetUserSSHKeySecret.
func (mr *MockClientInterfaceMockRecorder) GetUserSSHKeySecret(ctx, usernameSlug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSSHKeySecret", reflect.TypeOf((*MockClientInterface)(nil).GetUserSSHKeySecret), ctx, usernameSlug)
}

// GetUserServiceAccount mocks base method.
func (m *MockClientInterface) GetUserServiceAccount(ctx context.Context, usernameSlug string) (*v1.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserServiceAccount", ctx, usernameSlug)
	ret0, _ := ret[0].(*v1.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserServiceAccount indicates an expected call of GetUserServiceAccount.
func (mr *MockClientInterfaceMockRecorder) GetUserServiceAccount(ctx, usernameSlug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserServiceAccount", reflect.TypeOf((*MockClientInterface)(nil).GetUserServiceAccount), ctx, usernameSlug)
}

// IsUserToolPODRunning mocks base method.
func (m *MockClientInterface) IsUserToolPODRunning(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserToolPODRunning", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserToolPODRunning indicates an expected call of IsUserToolPODRunning.
func (mr *MockClientInterfaceMockRecorder) IsUserToolPODRunning(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserToolPODRunning", reflect.TypeOf((*MockClientInterface)(nil).IsUserToolPODRunning), ctx, username)
}

// UpdateSecret mocks base method.
func (m *MockClientInterface) UpdateSecret(ctx context.Context, name string, values, labels map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", ctx, name, values, labels)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockClientInterfaceMockRecorder) UpdateSecret(ctx, name, values, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockClientInterface)(nil).UpdateSecret), ctx, name, values, labels)
}

// UpdateUserSSHKeySecret mocks base method.
func (m *MockClientInterface) UpdateUserSSHKeySecret(ctx context.Context, user entity.User, public, private string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserSSHKeySecret", ctx, user, public, private)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserSSHKeySecret indicates an expected call of UpdateUserSSHKeySecret.
func (mr *MockClientInterfaceMockRecorder) UpdateUserSSHKeySecret(ctx, user, public, private interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserSSHKeySecret", reflect.TypeOf((*MockClientInterface)(nil).UpdateUserSSHKeySecret), ctx, user, public, private)
}
