name: Auto-assign
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: 'auto-assign issue'
        uses: kentaro-m/auto-assign-action@v2.0.0
