name: KDLServer Application Build

on:
  workflow_run:
    workflows:
      - "KAI Lab API - Quality Check"
      - "KAI Lab UI - Quality Check"
    types:
      - completed
    branches:
      - main
      - "release/v*"

concurrency: build_component

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: konstellation-io/github-workflows/.github/workflows/build.yaml@v1.7.6
    with:
      component: kdl-app
      component_helm_tag: kdlServer.image.tag
      component_path: app
      component_image: kdl-server
      component_app: true
      values_file: helm/kdl-server/values.yaml
      chart_file: helm/kdl-server/Chart.yaml
    secrets:
      pat: ${{ secrets.PATNAME }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
