name: "[Component] Releases"

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "app/**/*"
      - "backup/**/*"
      - "drone-authorizer/**/*"
      - "drone-oauth2-setup/**/*"
      - "mlflow/**/*"
      - "project-operator/**/*"
      - "repo-cloner/**/*"
      - "user-tools-operator/**/*"
      - "vscode/**/*"

jobs:
  create-tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'

      - name: Install NPM dependencies and create tag release
        run: |
          npm install
          yarn workspaces run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
