name: "[Component] Create releases"

on:
  workflow_dispatch:
    inputs:
      pre_release:
        description: 'Create pre-release?'
        required: true
        type: boolean

jobs:
  create-tag-release:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'

      - name: Install NPM dependencies and create tag release
        run: |
          npm install

          if [ "${{ github.event.inputs.pre_release }}" == "true" ]; then
            yarn workspaces run semantic-release --prerelease=rc
          else
            yarn workspaces run semantic-release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
