name: Drone Authorizer Component Build

on:
  pull_request:
    branches:
      - main
      - "release/v*"
    paths:
      - "drone-authorizer/**/*"
      - ".github/workflows/drone-authorizer*"
  push:
    branches:
      - main
      - "release/v*"
    paths:
      - "drone-authorizer/**/*"
      - ".github/workflows/drone-authorizer*"


jobs:

  lint-dockerfile:
    uses: konstellation-io/github-workflows/.github/workflows/lint-dockerfile.yaml@main
    with:
      component_path: drone-authorizer

  build:
    needs: lint-dockerfile
    uses: konstellation-io/github-workflows/.github/workflows/build.yaml@main
    with:
      component: drone-authorizer
      component_helm: droneAuthorizer
      component_path: drone-authorizer
      component_image: drone-authorizer
    secrets:
      github_token: ${{ secrets.PATNAME }}

