name: Fix

on:
  workflow_run:
    workflows:
      - "KDL Server App API Quality"
      - "KDL Server App UI Quality"
      - "KDL Server App Dockerfile Quality"
      - "KDL Server Backup Quality"
      - "KDL Server Cleaner Quality"
      - "KDL Server Drone Authorizer Quality"
      - "KDL Server Gitea OAuth2 Setup Quality"
      - "KDL Server MLFlow Quality"
      - "KDL Server Project Operator Quality"
      - "KDL Server User Tools Operator Quality"
      - "KDL Server VSCode Dockerfile Quality"
    branches: ["release-*"]
    types: 
      - completed

jobs:
  create-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate a fix
        uses: intelygenz/action-product-version-tags@v0.2.1
        with:
          prefix: "release-"
          mode: 'fix'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
