name: Gitea Oauth2 Setup Component Build

on:
  pull_request:
    branches:
      - main
      - "release/v*"
    paths:
      - "gitea-oauth2-setup/**/*"
      - ".github/workflows/gitea-oauth2-setup*"
  push:
    branches:
      - main
      - "release/v*"
    paths:
      - "gitea-oauth2-setup/**/*"
      - ".github/workflows/gitea-oauth2-setup*"


jobs:

  lint-dockerfile:
    uses: konstellation-io/github-workflows/.github/workflows/lint-dockerfile.yaml@main
    with:
      component_path: gitea-oauth2-setup

  build:
    needs: lint-dockerfile
    uses: konstellation-io/github-workflows/.github/workflows/build.yaml@main
    with:
      component: gitea-oauth2-setup
      component_helm: giteaOauth2Setup
      component_path: gitea-oauth2-setup
      component_image: gitea-oauth2-setup
      component_usertools_operator: true
      chart_name: kdl-server
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}

