name: Gitea Oauth2 Setup Component Build

on:
  pull_request:
    branches:
      - main
      - "release/v*"
    paths:
      - "gitea-oauth2-setup/**/*"
  push:
    branches:
      - main
      - "release/v*"
    paths:
      - "gitea-oauth2-setup/**/*"


jobs:
  lint-dockerfile:
    uses: konstellation-io/github-workflows/.github/workflows/lint-dockerfile.yaml@v1.3.0
    with:
      component_path: gitea-oauth2-setup

  build:
    needs: lint-dockerfile
    uses: konstellation-io/github-workflows/.github/workflows/build.yaml@v1.3.0
    with:
      component: gitea-oauth2-setup
      component_helm_tag: giteaOauth2Setup.image.tag
      component_path: gitea-oauth2-setup
      component_image: gitea-oauth2-setup
      values_file: helm/kdl-server/values.yaml
    secrets:
      pat: ${{ secrets.PATNAME }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_token: ${{ secrets.DOCKERHUB_TOKEN }}

