name: KDL Server Jupyter GPU Quality

on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - v*
    paths:
      - "jupyter-gpu/**/*"
      - ".github/workflows/kdl-server-jupyter-gpu-quality*"

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./jupyter-gpu/Dockerfile
          format: tty
          config: ./.hadolint.yml
