name: KDL Server Cleaner Quality

on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - v*
    paths:
      - "cleaner/**/*"
      - ".github/workflows/kdl-server-cleaner-quality*"

jobs:
  test-cleaner-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14' ]
    name: Go ${{ matrix.go }} testing
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./... -v -cover
        working-directory: cleaner
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./cleaner/Dockerfile
          format: tty
          config: ./.hadolint.yml
