name: KDL Server Drone Authorizer Quality

on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - v*
    paths:
      - "drone-authorizer/**/*"
      - ".github/workflows/kdl-server-drone-authorizer-quality*"

jobs:
  lint-drone-authorizer-dockerfile:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.1.1
      with:
        target: drone-authorizer/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
