name: KDL Server MLFlow Quality

on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - v*
    paths:
      - "mlflow/**/*"
      - ".github/workflows/kdl-server-mlflow-quality*"

jobs:
  lint-mlflow-dockerfile:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: mlflow/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}