name: KDL Server Backup Quality

on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - v*
    paths:
      - "backup/**/*"
      - ".github/workflows/kdl-server-backup-quality*"

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: ./backup/Dockerfile
          format: tty
          config: ./.hadolint.yml
