name: KDL Server Gitea OAuth2 Setup Quality

on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - v*
    paths:
      - "gitea-oauth2-setup/**/*"
      - ".github/workflows/kdl-server-gitea-oauth2-setup-quality*"

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: ./gitea-oauth2-setup/Dockerfile
        format: tty
        config: ./.hadolint.yml
