name: KDL Server Cleaner Quality

on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - v*
    paths:
      - "cleaner/**/*"
      - ".github/workflows/kdl-server-cleaner-quality*"

jobs:
  test-cleaner-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14' ]
    name: Go ${{ matrix.go }} testing
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./... -v -cover
        working-directory: cleaner
  lint-cleaner-dockerfile:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      with:
        target: cleaner/Dockerfile
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}