name: Knowledge Graph Quality
on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - v*
    paths:
      - "kg/**/*"
      - ".github/workflows/knowledge-graph*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      working-directory: kg
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --system --dev 
    - name: Run test
      working-directory: kg
      run: |
        pytest --cov=src --cov-report xml tests/unit
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 
        
    - name: Run linter
      working-directory: kg
      run: |
        flake8
