name: Knowledge Graph Quality
on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - v*
    paths:
      - "kg/**/*"
      - ".github/workflows/knowledge-graph*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      working-directory: kg
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --system --dev
        pip install pytest-cov
    - name: Run test
      working-directory: kg
      run: |
        coverage run --source=. -m py.test tests/unit/
        coverage xml -o ./coverage.xml
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: kg/coverage.xml
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 
        
    - name: Run linter
      working-directory: kg
      run: |
        flake8
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: 
      - test
      - lint
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Download code coverage results
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: kg
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: kg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_KG }}
