name: Pre Release

on:
  workflow_run:
    workflows:
      - "KDL Server App API Quality"
      - "KDL Server App UI Quality"
      - "Knowledge Graph Quality"
    branches: [main]
    types:
      - completed
  pull_request:
    branches: ["main"]
    tags-ignore: [v*]
    paths:
      - "project-operator/**/*"

jobs:
  generate-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate a pre-release
        uses: intelygenz/action-product-version-tags@v0.1.8
        with:
          current-major: 0
          prefix: "release-"
          mode: 'pre-release'
          pre-release: 'alpha'
          default-branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
