name: Pre Release

on:
  workflow_run:
    workflows:
      - "KDL Server App API Quality"
      - "KDL Server App UI Quality"
      - "KDL Server App Dockerfile Quality"
      - "KDL Server Backup Quality"
      - "KDL Server Cleaner Quality"
      - "KDL Server Drone Authorizer Quality"
      - "KDL Server MLFlow Quality"
      - "KDL Server Project Operator Quality"
      - "KDL Server User Tools Operator Quality"
    branches: [main]
    types:
      - completed

jobs:
  generate-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate a pre-release
        uses: intelygenz/action-product-version-tags@v0.2.1
        with:
          current-major: 0
          prefix: "release-"
          mode: 'pre-release'
          pre-release: 'alpha'
          default-branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.PATNAME }}
