name: "[KAI Lab UI] Quality Check"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'app/ui/*'
  push:
    paths:
      - 'app/ui/*'

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: app/ui/yarn.lock

      - name: Run UI ESLinter
        working-directory: ./app/ui
        run: |
          yarn install
          yarn run lint

      - name: UI Run tests
        working-directory: ./app/ui
        run: |
          yarn install
          yarn run test:cov:sonar

      - name: UI Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            ./app/ui/coverage
            ./app/ui/test-report.xml

      - name: UI Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          install: true
          working-directory: ./app/ui
          start: npm start
          browser: chrome
          wait-on: 'http://localhost:3001'
          wait-on-timeout: 120
        env:
          NODE_OPTIONS: --max-old-space-size=6144
