name: "[QA] Quality Checks UI"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'app/ui/*'
  push:
    paths:
      - 'app/ui/*'

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: app/ui/yarn.lock

      - name: Run UI ESLinter
        working-directory: ./app/ui
        run: |
          yarn install
          yarn run lint

      - name: UI Run tests
        working-directory: ./app/ui
        run: |
          yarn install
          yarn run test:cov:sonar

      - name: UI Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            ./app/ui/coverage
            ./app/ui/test-report.xml

      - name: UI Run e2e tests
        uses: cypress-io/github-action@v5
        with:
          install: true
          working-directory: ./app/ui
          start: npm start
          browser: chrome
          wait-on: 'http://localhost:3001'
          wait-on-timeout: 120
        env:
          NODE_OPTIONS: --max-old-space-size=6144

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: quality-checks
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Download code coverage results
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: app/ui

      - name: Fix code coverage paths
        working-directory: app/ui
        run: |
          sed -i 's|/home/runner/work/kdl-server/kdl-server/|/github/workspace/|g' coverage/lcov.info
          sed -i 's|/home/runner/work/kdl-server/kdl-server/|/github/workspace/|g' test-report.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: app/ui
