# TODO: refactor workflow when all components will migrate to
# each repository or move on same folder
#

name: "[Releases] Create"

env:
  COMPONENTS: "app,mlflow,filebrowser,project-operator,repo-cloner,user-tools-operator"

on:
  workflow_dispatch:
    inputs:
      component:
        description: 'Select a component for release'
        required: true
        type: choice
        options:
          - all
          - kdl-app
          - filebrowser
          - mlflow
          - project-operator
          - repo-cloner
          - user-tools-operator

  push:
    branches:
      - 'release/*'
      - 'hotfix/*'

jobs:
  manual-create-tag-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install NPM dependencies and create release
        run: |
          npm install

          if [[ "${{ github.event.inputs.component }}" == "all" || -z "${{ github.event.inputs.component }}" ]]; then
            echo "No specific components detected - releasing all workspaces"
            yarn workspaces run semantic-release
          else
            echo "Releasing component: ${{ github.event.inputs.component }}"
            yarn workspace ${{ github.event.inputs.component }} run semantic-release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  create-tag-release:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Detect changed components
        id: detect-components
        run: |
          COMPONENTS_LIST=""
          # releases or pre-releases always from main branch
          MERGE_BASE=$(git merge-base origin/main HEAD)

          for COMPONENT in $(echo ${{ env.COMPONENTS }} | tr ',' ' '); do
            if git diff --name-only $MERGE_BASE HEAD | grep -q "^$COMPONENT/"; then
              COMPONENTS_LIST="$COMPONENTS_LIST $COMPONENT"
            fi
          done

          COMPONENTS_LIST=$(echo $COMPONENTS_LIST | xargs)
          echo "Detected components: $COMPONENTS_LIST"
          echo "CHANGED_COMPONENTS=$COMPONENTS_LIST" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Create component releases
        run: |
          npm install

          if [ ! -z "${{ env.CHANGED_COMPONENTS }}" ]; then
            for COMPONENT in $(echo ${{ env.CHANGED_COMPONENTS }} | tr ',' ' '); do
              echo "Releasing component: $COMPONENT"
              yarn workspace $COMPONENT run semantic-release
            done
          else
            echo "No specific components detected - releasing all workspaces"
            yarn workspaces run semantic-release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
