# TODO: refactor workflow when all components will migrate to
# each repository or move on same folder
#

name: "[Releases] Create"

env:
  COMPONENTS: "app,backup,cleaner,drone-authorizer,gitea-oauth2-setup,mlflow,project-operator,repo-cloner,user-tools-operator,vscode"

on:
  workflow_dispatch:
    inputs:
      component:
        description: 'Select a component for release'
        required: true
        type: choice
        options:
          - all
          - app
          - backup
          - cleaner
          - drone-authorizer
          - gitea-oauth2-setup
          - mlflow
          - project-operator
          - repo-cloner
          - user-tools-operator
          - vscode

  push:
    branches:
      - 'release/*'

jobs:
  validate-conditions:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Validate release conditions
        run: |
          if [[ "${{ github.event.inputs.pre_release }}" == "false" && "${{ github.ref_name }}" != "main" ]]; then
            echo "Regular releases can only be created from the 'main' branch."
            exit 1
          else
            echo "Conditions are met for the release."
          fi

  manual-create-tag-release:
    runs-on: ubuntu-latest
    needs: validate-conditions
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'

      - name: Install NPM dependencies and create release
        run: |
          if [[ "${{ github.event.inputs.component }}" == "all" || -z "${{ github.event.inputs.component }}" ]]; then
            for COMPONENT in $(echo $COMPONENTS | tr ',' ' '); do
              echo "Releasing component: $COMPONENT"
              cd $COMPONENT && npm install && npx semantic-release
            done
          else
            echo "Releasing component: ${{ github.event.inputs.component }}"
            cd ${{ github.event.inputs.component }} && npm install && npx semantic-release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  prerelease-get-components:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Detect changed components
        id: detect-components
        run: |
          COMPONENTS_LIST=""
          for COMPONENT in $(echo $COMPONENTS | tr ',' ' '); do
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^$COMPONENT/"; then
              COMPONENTS_LIST="$COMPONENTS_LIST $COMPONENT"
            fi
          done

          # Remove leading or trailing spaces (if any)
          COMPONENTS_LIST=$(echo $COMPONENTS_LIST | xargs)

          echo "Detected components: $COMPONENTS_LIST"
          echo "changed-components=$COMPONENTS_LIST" >> $GITHUB_OUTPUT

  prerelease-create-tag:
    runs-on: ubuntu-latest
    needs: prerelease-get-components
    strategy:
      matrix:
        component: ${{ fromJson(needs.determine-components.outputs.changed-components) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'

      - name: Create release for changed component
        working-directory: ${{ matrix.component }}
        run: |
          npm install && npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
