name: "[GitHub] Mark stale issues and PRs"
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest

    # ref: https://github.com/actions/stale?tab=readme-ov-file#recommended-permissions
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity.'
          stale-pr-message: 'This pull request is stale because it has been open 60 days with no activity.'
          days-before-stale: 60
          days-before-close: -1
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
