linters:
  enable-all: true
  disable:
    - gci
    - gofumpt
    - paralleltest
    - testpackage
    - exportloopref
    - gomnd
    - execinquery
# all available settings of specific linters
linters-settings:
  unparam:
    check-exported: true
  funlen:
    lines: 120
    statements: 80
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        allow:
          - cleaner
